### ISSUE TITLE
Travis Node Version Support Update

### ISSUE THREAD

**Issue by JacobMGEvans** [koajs/router#61]
To avoid breaking builds and to update the Travis pipeline, bumping the Node versions to be more in line with Node release support can be implemented like this example. 

[v10 & v11 are LTS (long term support) ](https://nodejs.org/en/about/releases/)

```yml
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
notifications:
  email:
    on_success: never
```
